from __future__ import annotations

from django.urls import path

from .views import (
    AdminImageUploadView,
    AdminHighlightItemCreateView,
    AdminHighlightItemDetailView,
    AdminHighlightReorderView,
    AdminHighlightStageCreateView,
    AdminHighlightStageDetailView,
    AdminHighlightsView,
    AdminObsidianReconcileView,
    AdminObsidianSyncView,
    AdminPingView,
    AdminPhotoDetailView,
    AdminPhotoListCreateView,
    AdminPhotoReorderView,
    AdminPostDetailView,
    AdminPostListCreateView,
    AdminSocialDetailView,
    AdminSocialListCreateView,
    AdminSocialReorderView,
    AdminTimelineDetailView,
    AdminTimelineListCreateView,
    AdminTimelineReorderView,
    AdminTravelDetailView,
    AdminTravelListCreateView,
    AdminTravelReorderView,
    HealthCheckView,
    HighlightsView,
    HomeView,
    IncrementPostView,
    LoginView,
    LogoutView,
    MeView,
    PhotoWallView,
    PostDetailView,
    PostListView,
    SocialGraphView,
    TimelineView,
    TravelView,
)

urlpatterns = [
    path("health", HealthCheckView.as_view(), name="health"),
    path("home/", HomeView.as_view(), name="home"),
    path("posts/", PostListView.as_view(), name="posts-list"),
    path("posts/<slug:slug>/", PostDetailView.as_view(), name="posts-detail"),
    path("posts/<slug:slug>/view/", IncrementPostView.as_view(), name="posts-view"),
    path("timeline/", TimelineView.as_view(), name="timeline"),
    path("highlights/", HighlightsView.as_view(), name="highlights"),
    path("travel/", TravelView.as_view(), name="travel"),
    path("social-graph/", SocialGraphView.as_view(), name="social-graph"),
    path("photo-wall/", PhotoWallView.as_view(), name="photo-wall"),
    path("auth/login", LoginView.as_view(), name="auth-login"),
    path("auth/logout", LogoutView.as_view(), name="auth-logout"),
    path("auth/me", MeView.as_view(), name="auth-me"),
    path("admin/ping", AdminPingView.as_view(), name="admin-ping"),
    path("admin/images/", AdminImageUploadView.as_view(), name="admin-images"),
    path("admin/posts", AdminPostListCreateView.as_view(), name="admin-posts"),
    path("admin/posts/", AdminPostListCreateView.as_view()),
    path("admin/posts/<int:post_id>", AdminPostDetailView.as_view(), name="admin-post-detail"),
    path("admin/posts/<int:post_id>/", AdminPostDetailView.as_view()),
    path("admin/timeline", AdminTimelineListCreateView.as_view(), name="admin-timeline"),
    path("admin/timeline/", AdminTimelineListCreateView.as_view()),
    path("admin/timeline/reorder", AdminTimelineReorderView.as_view(), name="admin-timeline-reorder"),
    path("admin/timeline/reorder/", AdminTimelineReorderView.as_view()),
    path("admin/timeline/<int:timeline_id>", AdminTimelineDetailView.as_view(), name="admin-timeline-detail"),
    path("admin/timeline/<int:timeline_id>/", AdminTimelineDetailView.as_view()),
    path("admin/travel", AdminTravelListCreateView.as_view(), name="admin-travel"),
    path("admin/travel/", AdminTravelListCreateView.as_view()),
    path("admin/travel/reorder", AdminTravelReorderView.as_view(), name="admin-travel-reorder"),
    path("admin/travel/reorder/", AdminTravelReorderView.as_view()),
    path("admin/travel/<int:travel_id>", AdminTravelDetailView.as_view(), name="admin-travel-detail"),
    path("admin/travel/<int:travel_id>/", AdminTravelDetailView.as_view()),
    path("admin/social", AdminSocialListCreateView.as_view(), name="admin-social"),
    path("admin/social/", AdminSocialListCreateView.as_view()),
    path("admin/social-graph", AdminSocialListCreateView.as_view(), name="admin-social-graph"),
    path("admin/social-graph/", AdminSocialListCreateView.as_view()),
    path("admin/social/reorder", AdminSocialReorderView.as_view(), name="admin-social-reorder"),
    path("admin/social/reorder/", AdminSocialReorderView.as_view()),
    path("admin/social/<int:social_id>", AdminSocialDetailView.as_view(), name="admin-social-detail"),
    path("admin/social/<int:social_id>/", AdminSocialDetailView.as_view()),
    path("admin/photos", AdminPhotoListCreateView.as_view(), name="admin-photos"),
    path("admin/photos/", AdminPhotoListCreateView.as_view()),
    path("admin/photos/reorder", AdminPhotoReorderView.as_view(), name="admin-photos-reorder"),
    path("admin/photos/reorder/", AdminPhotoReorderView.as_view()),
    path("admin/photos/<int:photo_id>", AdminPhotoDetailView.as_view(), name="admin-photo-detail"),
    path("admin/photos/<int:photo_id>/", AdminPhotoDetailView.as_view()),
    path("admin/highlights", AdminHighlightsView.as_view(), name="admin-highlights"),
    path("admin/highlights/", AdminHighlightsView.as_view()),
    path("admin/highlights/stages", AdminHighlightStageCreateView.as_view(), name="admin-highlight-stage-create"),
    path("admin/highlights/stages/", AdminHighlightStageCreateView.as_view()),
    path("admin/highlights/stages/<int:stage_id>", AdminHighlightStageDetailView.as_view(), name="admin-highlight-stage-detail"),
    path("admin/highlights/stages/<int:stage_id>/", AdminHighlightStageDetailView.as_view()),
    path("admin/highlights/items", AdminHighlightItemCreateView.as_view(), name="admin-highlight-item-create"),
    path("admin/highlights/items/", AdminHighlightItemCreateView.as_view()),
    path("admin/highlights/items/<int:item_id>", AdminHighlightItemDetailView.as_view(), name="admin-highlight-item-detail"),
    path("admin/highlights/items/<int:item_id>/", AdminHighlightItemDetailView.as_view()),
    path("admin/highlights/reorder", AdminHighlightReorderView.as_view(), name="admin-highlights-reorder"),
    path("admin/highlights/reorder/", AdminHighlightReorderView.as_view()),
    path("admin/obsidian-sync/", AdminObsidianSyncView.as_view(), name="admin-obsidian-sync"),
    path("admin/obsidian-sync/reconcile/", AdminObsidianReconcileView.as_view(), name="admin-obsidian-reconcile"),
]
