/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        theme: {
          bg: "rgb(var(--theme-bg) / <alpha-value>)",
          surface: "rgb(var(--theme-surface) / <alpha-value>)",
          "surface-raised": "rgb(var(--theme-surface-raised) / <alpha-value>)",
          accent: "rgb(var(--theme-accent) / <alpha-value>)",
          "accent-soft": "rgb(var(--theme-accent-soft) / <alpha-value>)",
          ink: "rgb(var(--theme-ink) / <alpha-value>)",
          muted: "rgb(var(--theme-muted) / <alpha-value>)",
          soft: "rgb(var(--theme-soft) / <alpha-value>)",
          line: "rgb(var(--theme-line) / <alpha-value>)",
          "line-strong": "rgb(var(--theme-line-strong) / <alpha-value>)",
        },
        claude: {
          parchment: "#f5f4ed",
          ivory: "#faf9f5",
          "warm-sand": "#e8e6dc",
          "border-cream": "#f0eee6",
          "border-warm": "#e8e6dc",
          "ring-warm": "#d1cfc5",
          "ring-deep": "#c2c0b6",
          terracotta: "#c96442",
          coral: "#d97757",
          "near-black": "#141413",
          "deep-dark": "#141413",
          "dark-surface": "#30302e",
          "dark-warm": "#3d3d3a",
          "charcoal-warm": "#4d4c48",
          "olive-gray": "#5e5d59",
          "stone-gray": "#87867f",
          "warm-silver": "#b0aea5",
          "error-crimson": "#b53333",
          "focus-blue": "#3898ec",
        },
        slate: {
          50: "#f5f4ed",
          100: "#f0eee6",
          200: "#e8e6dc",
          300: "#d1cfc5",
          400: "#87867f",
          500: "#5e5d59",
          600: "#4d4c48",
          700: "#3d3d3a",
          800: "#30302e",
          900: "#141413",
          950: "#0a0a09",
        },
      },
      fontFamily: {
        "theme-display": ["var(--theme-font-display)"],
        "theme-body": ["var(--theme-font-body)"],
        "theme-sans": ["var(--theme-font-sans)"],
        serif: [
          '"Source Serif 4"',
          '"Source Serif Pro"',
          "Georgia",
          '"LXGW WenKai"',
          '"Kaiti SC"',
          "STKaiti",
          '"PingFang SC"',
          "serif",
        ],
        display: [
          '"Source Serif 4"',
          '"Source Serif Pro"',
          "Georgia",
          '"LXGW WenKai"',
          "serif",
        ],
        sans: [
          '"Inter"',
          "system-ui",
          '"PingFang SC"',
          '"Hiragino Sans GB"',
          '"Microsoft YaHei"',
          "sans-serif",
        ],
        mono: [
          '"JetBrains Mono"',
          '"SFMono-Regular"',
          "Menlo",
          "monospace",
        ],
      },
      borderRadius: {
        "claude-sm": "6px",
        claude: "8px",
        "claude-md": "12px",
        "claude-lg": "16px",
        "claude-xl": "24px",
        "claude-2xl": "32px",
      },
      boxShadow: {
        "ring-warm": "0 0 0 1px #d1cfc5",
        "ring-deep": "0 0 0 1px #c2c0b6",
        "ring-dark": "0 0 0 1px #30302e",
        "ring-terracotta": "0 0 0 1px #c96442",
        whisper: "rgba(0, 0, 0, 0.05) 0px 4px 24px",
        "whisper-lg": "rgba(0, 0, 0, 0.06) 0px 8px 32px",
      },
      lineHeight: {
        "claude-tight": "1.10",
        "claude-heading": "1.20",
        "claude-relaxed": "1.60",
      },
    },
  },
  plugins: [],
};
