# Generated by Django 5.2.11 on 2026-02-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialfriend',
            name='stage_key',
            field=models.CharField(choices=[('primary', '小学'), ('middle', '初中'), ('high', '高中'), ('tongji', '同济'), ('zju', '浙大'), ('career', '工作'), ('family', '家庭')], default='career', max_length=20),
        ),
    ]
