# Generated by Django 5.2.11 on 2026-02-14 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_socialfriend_stage_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(choices=[("api", "API"), ("command", "Command")], default="api", max_length=20)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("mode", models.CharField(choices=[("overwrite", "覆盖"), ("skip", "跳过"), ("merge", "合并")], default="overwrite", max_length=20)),
                ("action", models.CharField(choices=[("created", "创建"), ("updated", "更新"), ("skipped", "跳过"), ("failed", "失败")], default="created", max_length=20)),
                ("status", models.CharField(choices=[("success", "成功"), ("failed", "失败"), ("dry_run", "预演")], default="success", max_length=20)),
                ("message", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                (
                    "operator",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sync_logs", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"ordering": ["-started_at", "-id"]},
        ),
    ]
