# Generated by Django 5.2.11 on 2026-02-15 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_synclog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlightitem',
            options={'ordering': ['sort_order', 'achieved_at', 'id'], 'verbose_name': '高光条目', 'verbose_name_plural': '高光条目'},
        ),
        migrations.AlterModelOptions(
            name='highlightstage',
            options={'ordering': ['sort_order', 'start_date', 'id'], 'verbose_name': '高光阶段', 'verbose_name_plural': '高光阶段'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='postview',
            options={'ordering': ['-views'], 'verbose_name': '文章阅读', 'verbose_name_plural': '文章阅读'},
        ),
        migrations.AlterModelOptions(
            name='socialfriend',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': '社交图谱', 'verbose_name_plural': '社交图谱'},
        ),
        migrations.AlterModelOptions(
            name='synclog',
            options={'ordering': ['-started_at', '-id'], 'verbose_name': '同步日志', 'verbose_name_plural': '同步日志'},
        ),
        migrations.AlterModelOptions(
            name='timelinenode',
            options={'ordering': ['sort_order', 'start_date'], 'verbose_name': '人生足迹', 'verbose_name_plural': '人生足迹'},
        ),
        migrations.AlterModelOptions(
            name='travelplace',
            options={'ordering': ['sort_order', 'province', 'city'], 'verbose_name': '旅行足迹', 'verbose_name_plural': '旅行足迹'},
        ),
    ]
