# Generated by Django 5.2.11 on 2026-02-15

from django.db import migrations, models


def backfill_honorific(apps, schema_editor):
    SocialFriend = apps.get_model("blog", "SocialFriend")

    female_markers = ("女士", "女友", "妻", "太太", "妈妈", "母亲", "姐姐", "妹妹", "闺蜜")
    male_markers = ("先生", "男友", "丈夫", "爸爸", "父亲", "哥哥", "弟弟", "师兄")

    for friend in SocialFriend.objects.all():
        context_text = f"{friend.relation or ''} {friend.public_label or ''}"
        if any(marker in context_text for marker in female_markers):
            friend.honorific = "ms"
            friend.save(update_fields=["honorific"])
            continue
        if any(marker in context_text for marker in male_markers):
            friend.honorific = "mr"
            friend.save(update_fields=["honorific"])


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_highlightitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialfriend",
            name="honorific",
            field=models.CharField(
                choices=[("mr", "先生"), ("ms", "女士")],
                default="mr",
                max_length=10,
            ),
        ),
        migrations.RunPython(backfill_honorific, migrations.RunPython.noop),
    ]
