# Generated by Django 5.2.11 on 2026-02-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_socialfriend_honorific"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialfriend",
            name="contact",
            field=models.CharField(blank=True, max_length=255, verbose_name="联系方式"),
        ),
    ]
