# Generated by Django 5.2.11 on 2026-02-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_socialfriend_contact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ObsidianSyncRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("trigger", models.CharField(choices=[("scheduled", "定时"), ("manual", "手动")], default="manual", max_length=20)),
                ("status", models.CharField(choices=[("success", "成功"), ("failed", "失败")], default="success", max_length=20)),
                ("repo_url", models.CharField(blank=True, max_length=500)),
                ("repo_branch", models.CharField(blank=True, max_length=100)),
                ("repo_commit", models.CharField(blank=True, max_length=64)),
                ("scanned_count", models.PositiveIntegerField(default=0)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("missing_count", models.PositiveIntegerField(default=0)),
                ("published_updated_count", models.PositiveIntegerField(default=0)),
                ("drafted_count", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("message", models.TextField(blank=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="obsidian_sync_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Obsidian 同步运行",
                "verbose_name_plural": "Obsidian 同步运行",
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ObsidianDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("vault_path", models.CharField(db_index=True, max_length=500, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("slug_candidate", models.SlugField(blank=True, max_length=255)),
                ("category_candidate", models.CharField(choices=[("tech", "技术"), ("learning", "效率"), ("life", "生活")], default="learning", max_length=20)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("has_publish_tag", models.BooleanField(db_index=True, default=False)),
                ("content", models.TextField(blank=True)),
                ("excerpt", models.TextField(blank=True)),
                ("file_hash", models.CharField(blank=True, max_length=40)),
                ("source_mtime", models.DateTimeField(blank=True, null=True)),
                ("source_exists", models.BooleanField(db_index=True, default=True)),
                ("first_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_indexed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "linked_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="obsidian_documents",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obsidian 文档池",
                "verbose_name_plural": "Obsidian 文档池",
                "ordering": ["-last_indexed_at", "vault_path"],
            },
        ),
    ]
