# Generated by Django 5.2.11 on 2026-02-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_socialfriend_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoWallImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(max_length=800)),
                ("source_url", models.URLField(blank=True, max_length=800)),
                ("captured_at", models.DateField(blank=True, null=True)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "verbose_name": "照片墙",
                "verbose_name_plural": "照片墙",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
