# Generated by Django 5.2.11 on 2026-02-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_photowallimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialfriend",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="生日"),
        ),
    ]
