# Generated by Django 5.2.11 on 2026-02-15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_socialfriend_birthday"),
        ("blog", "0007_obsidian_document_pool"),
    ]

    operations = []
