# Generated by Django 5.2.11 on 2026-02-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_photowallimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeStatsSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("snapshot_date", models.DateField(db_index=True, unique=True)),
                ("views_total", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "首页统计快照",
                "verbose_name_plural": "首页统计快照",
                "ordering": ["-snapshot_date"],
            },
        ),
    ]
