# Generated by Django 5.2.11 on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_socialfriend_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialfriend",
            name="honorific",
            field=models.CharField(
                choices=[
                    ("mr", "先生"),
                    ("ms", "女士"),
                    ("classmate", "同学"),
                    ("junior_m", "学弟"),
                    ("junior_f", "学妹"),
                    ("senior_m", "师兄"),
                    ("teacher", "老师"),
                ],
                default="mr",
                max_length=10,
            ),
        ),
    ]
