# Generated by Django 5.2.11 on 2026-02-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_sitevisit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sitevisit',
            new_name='blog_sitevi_path_89a6b2_idx',
            old_name='blog_sitevi_path_0b4d3c_idx',
        ),
        migrations.RenameIndex(
            model_name='sitevisit',
            new_name='blog_sitevi_referre_730121_idx',
            old_name='blog_sitevi_referre_a1c8e2_idx',
        ),
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False, verbose_name='置顶'),
        ),
        migrations.AddField(
            model_name='post',
            name='pin_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='置顶排序'),
        ),
    ]
