# Generated by Django 5.2.11 on 2026-02-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('html_url', models.URLField(max_length=500)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('homepage_url', models.URLField(blank=True, max_length=500)),
                ('stars_count', models.PositiveIntegerField(default=0)),
                ('forks_count', models.PositiveIntegerField(default=0)),
                ('open_issues_count', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('cover', models.URLField(blank=True, max_length=500)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '开源项目',
                'verbose_name_plural': '开源项目',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
