# Generated by Django 5.2.11 on 2026-02-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_add_github_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("likes", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "首页点赞",
                "verbose_name_plural": "首页点赞",
            },
        ),
        migrations.CreateModel(
            name="HomeLikeVote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "首页点赞投票",
                "verbose_name_plural": "首页点赞投票",
            },
        ),
    ]
