# Generated by Django 5.2.11 on 2026-02-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_barrage_comment"),
        ("blog", "0019_home_like"),
    ]

    operations = []
