# Generated by Django 5.2.11 on 2026-02-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_merge_0018_barrage_comment_0019_home_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeriesConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(default='default', unique=True)),
                ('x_axis', models.JSONField(blank=True, default=list)),
                ('series', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '时间分配图配置',
                'verbose_name_plural': '时间分配图配置',
                'ordering': ['key'],
            },
        ),
    ]
