# Generated by Django 5.2.11 on 2026-02-23 12:41

from django.db import migrations, models


def seed_radar_configs(apps, schema_editor):
    RadarConfig = apps.get_model("blog", "RadarConfig")
    RadarConfig.objects.get_or_create(
        key="work-writing",
        defaults={
            "title": "工作/文章能力谱",
            "subtitle": "工程实践与内容沉淀",
            "metrics": [
                {"label": "系统设计", "value": 86},
                {"label": "工程交付", "value": 88},
                {"label": "问题拆解", "value": 85},
                {"label": "技术写作", "value": 90},
                {"label": "研究输出", "value": 84},
                {"label": "协作沟通", "value": 80},
                {"label": "长期迭代", "value": 92},
            ],
            "sort_order": 0,
            "is_active": True,
        },
    )
    RadarConfig.objects.get_or_create(
        key="interest-life",
        defaults={
            "title": "兴趣爱好能力谱",
            "subtitle": "生活节奏与持续探索",
            "metrics": [
                {"label": "旅行探索", "value": 86},
                {"label": "运动习惯", "value": 84},
                {"label": "阅读输入", "value": 88},
                {"label": "效率实验", "value": 92},
                {"label": "表达分享", "value": 85},
                {"label": "关系经营", "value": 89},
                {"label": "自我复盘", "value": 94},
            ],
            "sort_order": 1,
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_timeseriesconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='副标题')),
                ('metrics', models.JSONField(default=list, help_text='JSON数组, 每项含 {"label": "维度名", "value": 86}', verbose_name='维度数据')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '雷达图配置',
                'verbose_name_plural': '雷达图配置',
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.RunPython(seed_radar_configs, migrations.RunPython.noop),
    ]
