# Generated by Django 5.2.11 on 2026-02-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_seed_time_series_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.CharField(choices=[('after_marquee', '高光成就 → 代码项目之间'), ('after_game', '互动游戏 → 生活之间'), ('after_dream', '心愿清单 → 统计之间')], db_index=True, max_length=30)),
                ('category', models.CharField(choices=[('技术', '技术'), ('生活', '生活'), ('整理', '整理')], max_length=10)),
                ('lead', models.CharField(max_length=200)),
                ('emphasis', models.CharField(max_length=100)),
                ('tail', models.CharField(blank=True, default='。', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': '散落的文字',
                'verbose_name_plural': '散落的文字',
                'ordering': ['slot', 'sort_order'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('slot',), name='unique_active_quote_per_slot')],
            },
        ),
    ]
