# Generated by Django 5.2.11 on 2026-02-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_fill_travel_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubproject',
            name='description_zh',
            field=models.TextField(blank=True, verbose_name='中文简介'),
        ),
        migrations.AddField(
            model_name='githubproject',
            name='detail_en',
            field=models.TextField(blank=True, verbose_name='英文详情'),
        ),
        migrations.AddField(
            model_name='githubproject',
            name='detail_zh',
            field=models.TextField(blank=True, verbose_name='中文详情'),
        ),
        migrations.AddField(
            model_name='githubproject',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list, verbose_name='技术栈'),
        ),
    ]
