# Generated by Hermes
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0045_set_shanghai_jingan_current_residence"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(max_length=50, verbose_name="平台"),
                ),
                (
                    "account_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="账号名"
                    ),
                ),
                (
                    "date",
                    models.DateField(verbose_name="数据日期"),
                ),
                (
                    "followers",
                    models.IntegerField(default=0, verbose_name="粉丝数"),
                ),
                (
                    "total_views",
                    models.IntegerField(default=0, verbose_name="累计播放/阅读"),
                ),
                (
                    "total_likes",
                    models.IntegerField(default=0, verbose_name="累计获赞"),
                ),
                (
                    "posts_count",
                    models.IntegerField(default=0, verbose_name="内容数"),
                ),
                (
                    "comments",
                    models.IntegerField(default=0, verbose_name="评论数"),
                ),
                (
                    "shares",
                    models.IntegerField(default=0, verbose_name="分享数"),
                ),
                (
                    "favorites",
                    models.IntegerField(default=0, verbose_name="收藏数"),
                ),
                (
                    "best_post_title",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="最佳内容标题"
                    ),
                ),
                (
                    "best_post_views",
                    models.IntegerField(default=0, verbose_name="最佳内容播放"),
                ),
                (
                    "best_post_likes",
                    models.IntegerField(default=0, verbose_name="最佳内容赞"),
                ),
                (
                    "best_post_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="最佳内容链接"
                    ),
                ),
                (
                    "yesterday_followers",
                    models.IntegerField(default=0, verbose_name="昨日新增粉丝"),
                ),
                (
                    "yesterday_views",
                    models.IntegerField(default=0, verbose_name="昨日阅读/播放"),
                ),
                (
                    "yesterday_shares",
                    models.IntegerField(default=0, verbose_name="昨日分享"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="排序"
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="采集时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "自媒体数据",
                "verbose_name_plural": "自媒体数据",
                "db_table": "social_media_stats",
                "ordering": ["-collected_at"],
            },
        ),
    ]
