# Generated by Django 5.2.11 on 2026-05-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_obsidian_books_wishes_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='photowallimage',
            name='obsidian_path',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AddField(
            model_name='photowallimage',
            name='sync_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
